apiVersion: v1
data:
  storageclass.default: rook-ceph-block
  storageclass.list: rook-ceph-block,rook-cephfs
    #kubernetes_cluster_type: cncf
kind: ConfigMap
metadata:
  labels:
  name: ibm-cpp-config
