apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: operand-deployment-lifecycle-manager.v4.3.8
  namespace: {{ .Values.namespace }}
rules:
- apiGroups:
  - operators.coreos.com
  resourceNames:
  - operand-deployment-lifecycle-manager.v4.3.8
  resources:
  - operatorconditions
  verbs:
  - get
  - update
  - patch
